### ISSUE TITLE
problem when i tried it

### ISSUE THREAD

**Issue by daciansolgen** [vaahtokarkki/Avaruussaa#2]
Traceback (most recent call last):
  File "main.py", line 14, in <module>
    jodelInstance = Jodel()
  File "/mnt/c/Users/user/Desktop/Avaruussaa-master/Jodel.py", line 33, in __init__
    self.db = Database()
  File "/mnt/c/Users/user/Desktop/Avaruussaa-master/Database.py", line 39, in __init__
    self.db = client.get_default_database()
  File "/home/user/.local/lib/python3.6/site-packages/pymongo/mongo_client.py", line 1565, in get_default_database
    raise ConfigurationError('No default database defined')
pymongo.errors.ConfigurationError: No default database defined

**Comment by vaahtokarkki** [comment]
This project is deprecated as Jodel does not have any public api and jodel_api [is not maintained](https://github.com/nborrmann/jodel_api/issues/39) any more.
